title: Byungeun's Blog
description: Java / Python / Swift / Javascript / Spring / Django

url: http://blog.scogel.me
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 #- title: Contact
   #url: /contact

social:
   github: abyungeun
   #twitter: abyungeun
   facebook: WooByungEun
   email: abyungeun@gmail.com

google_analytics: "UA-58263416-1"
